---
title: "simplex_summary"
author: "Josh Justison"
date: "1/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

nlayers<-11
npoints<-61 

hyb_pos<-rep(NA,npoints)
hyb_neu<-rep(NA,npoints)
hyb_neg<-rep(NA,npoints)

i<-0
layer_space<-1/(nlayers-1)
for(div in seq(from=-1,to=1,length.out=nlayers)){
  leftover<-1-abs(div)
  
  hyb_zero<-seq(0,leftover,by=layer_space)
  
  leftover_leftover<-leftover-hyb_zero
  hyb_plus<- (div+1-hyb_zero)/2
  hyb_minus<-hyb_plus-div
  
  nvals<-length(hyb_minus)
  
  hyb_pos[(i+1):(i+nvals)]<-hyb_plus
  hyb_neg[(i+1):(i+nvals)]<-hyb_minus
  hyb_neu[(i+1):(i+nvals)]<-hyb_zero
  
  i<-i+nvals
}
dat<-data.frame(hyb_pos,hyb_neg,hyb_neu)

```


### Tree Based Phylogenies

```{r,echo=F}
library(Ternary)
library(tidyr)
library(dplyr)
path<-'../data'


nsims<-61

col_names<- c('rets'	,'tips','level','tree_child','tree_based','fu_stable','gen_no','degen_no','neu_no','recon','row_num')
my_frame<-as.data.frame(matrix(NA,nrow = 20000*nsims,ncol=length(col_names)))
colnames(my_frame)<- col_names
frame2<-as.data.frame(matrix(NA,nrow = 10000*nsims,ncol=3))
colnames(frame2)<-c('rets','tips')
count<-0
n1<-rep(NA,nsims)
n2<-rep(NA,nsims)
n3<-rep(NA,nsims)

  file_name_base<-paste(path,'/simplex/',sep='')
  
  rows<-1:nsims
  for(rw in rows){
    file_name<-paste(file_name_base,'row_',rw,'/phydata.csv',sep = '')

    
    
    dat <- read.csv(file =file_name)[,-1]
    nrows<-nrow(dat)
    frame2$rets[((count*nrows)+1):((count+1)*nrows)]<-dat$rec_rets/dat$rets
    frame2$tips[((count*nrows)+1):((count+1)*nrows)]<-dat$rec_tips/dat$tips
    frame2$row_num[((count*nrows)+1):((count+1)*nrows)] <-rw
    
    
    to_bind<-dat[,10:18]
    dat<-dat[,-(10:18)]
    colnames(to_bind)<-colnames(dat)
    recon<-c(rep(F,nrows),rep(T,nrows))
    row_row<-rep(rw,2*nrows)
    dat<-rbind(dat,to_bind)
    dat<-cbind(dat,recon,row_row)
    
    my_frame[((count*2*nrows)+1):((count+1)*2*nrows),]<-dat
    count<-count+1
  }


my_frame$rets[is.nan(my_frame$rets)]<-0
my_frame<-as_tibble(my_frame)

summed<- my_frame %>% 
  group_by(row_num,recon) %>%
  summarize(tc = sum(tree_child)/n(),
            tb = sum(tree_based)/n(),
            fus= sum(fu_stable)/n(),
            ratio = mean(rets/tips),
            tips = mean(tips),
            gen = mean(gen_no/rets,na.rm=T),
            degen = mean(degen_no/rets,na.rm=T),
            neu = mean(neu_no/rets,na.rm=T))
recon_dat <- summed %>% filter(recon==T)
complete_dat <- summed %>% filter(recon==F)



nlayers<-11
npoints<-61 

hyb_pos<-rep(NA,npoints)
hyb_neu<-rep(NA,npoints)
hyb_neg<-rep(NA,npoints)

i<-0
layer_space<-1/(nlayers-1)
for(div in seq(from=-1,to=1,length.out=nlayers)){
  leftover<-1-abs(div)
  
  hyb_zero<-seq(0,leftover,by=layer_space)
  
  leftover_leftover<-leftover-hyb_zero
  hyb_plus<- (div+1-hyb_zero)/2
  hyb_minus<-hyb_plus-div
  
  nvals<-length(hyb_minus)
  
  hyb_pos[(i+1):(i+nvals)]<-hyb_plus
  hyb_neg[(i+1):(i+nvals)]<-hyb_minus
  hyb_neu[(i+1):(i+nvals)]<-hyb_zero
  
  i<-i+nvals
}
dat<-data.frame(hyb_pos,hyb_neg,hyb_neu)










rbPal <- colorRampPalette(c('red','blue'))

#This adds a column of color values
# based on the y values

layout(matrix(1:2,ncol=2), width = c(2,1),height = c(1,1))
y_vals<-complete_dat$tb
cols <- rbPal(20)[as.numeric(cut(y_vals,breaks = 20))]

{
TernaryPlot(point='le',main='Complete Phylogenies',
            btip = expression(nu['+']),
            ctip = expression(nu['-']),
            atip = expression(nu['0']),
            axis.labels = seq(0,1,by=0.1),axis.cex=0.5
)
TernaryPoints(dat[1:59,c(3,1,2)],pch=19,col=cols,cex=2)
}
{
legend_image <- as.raster(matrix(rev(rbPal(20)), ncol=1))
plot(c(0,2),c(0,1),type = 'n', axes = F,xlab = '', ylab = '', main = 'Proportion Tree-Based')
text(x=1.5, y = seq(0,1,l=5), labels = round(seq(min(y_vals),max(y_vals),l=5),digits = 3))
rasterImage(legend_image, 0, 0, 1,1)
}

```

```{r,echo=F}
layout(matrix(1:2,ncol=2), width = c(2,1),height = c(1,1))
y_vals<-recon_dat$tb
cols <- rbPal(20)[as.numeric(cut(y_vals,breaks = 20))]

{
TernaryPlot(point='le', main='Recon Phylogenies',
            btip = expression(nu['+']),
            ctip = expression(nu['-']),
            atip = expression(nu['0']),
            axis.labels = seq(0,1,by=0.1),axis.cex=0.5
)
TernaryPoints(dat[1:59,c(3,1,2)],pch=19,col=cols,cex=2)
}
{
legend_image <- as.raster(matrix(rev(rbPal(20)), ncol=1))
plot(c(0,2),c(0,1),type = 'n', axes = F,xlab = '', ylab = '', main = 'Proportion Tree-Based')
text(x=1.5, y = seq(0,1,l=5), labels = round(seq(min(y_vals),max(y_vals),l=5),digits = 3))
rasterImage(legend_image, 0, 0, 1,1)
}

```

### FU Stable

```{r,echo=F}
layout(matrix(1:2,ncol=2), width = c(2,1),height = c(1,1))
y_vals<-complete_dat$fus
cols <- rbPal(20)[as.numeric(cut(y_vals,breaks = 20))]

{
TernaryPlot(point='le',main='Complete Phylogenies',
            btip = expression(nu['+']),
            ctip = expression(nu['-']),
            atip = expression(nu['0']),
            axis.labels = seq(0,1,by=0.1),axis.cex=0.5
)
TernaryPoints(dat[1:59,c(3,1,2)],pch=19,col=cols,cex=2)
}
{
legend_image <- as.raster(matrix(rev(rbPal(20)), ncol=1))
plot(c(0,2),c(0,1),type = 'n', axes = F,xlab = '', ylab = '', main = 'Proportion FU-Stable')
text(x=1.5, y = seq(0,1,l=5), labels = round(seq(min(y_vals),max(y_vals),l=5),digits = 3))
rasterImage(legend_image, 0, 0, 1,1)
}

```

```{r,echo=F}
layout(matrix(1:2,ncol=2), width = c(2,1),height = c(1,1))
y_vals<-recon_dat$fus
cols <- rbPal(20)[as.numeric(cut(y_vals,breaks = 20))]

{
TernaryPlot(point='le', main='Recon Phylogenies',
            btip = expression(nu['+']),
            ctip = expression(nu['-']),
            atip = expression(nu['0']),
            axis.labels = seq(0,1,by=0.1),axis.cex=0.5
)
TernaryPoints(dat[1:59,c(3,1,2)],pch=19,col=cols,cex=2)
}
{
legend_image <- as.raster(matrix(rev(rbPal(20)), ncol=1))
plot(c(0,2),c(0,1),type = 'n', axes = F,xlab = '', ylab = '', main = 'Proportion FU-Stable')
text(x=1.5, y = seq(0,1,l=5), labels = round(seq(min(y_vals),max(y_vals),l=5),digits = 3))
rasterImage(legend_image, 0, 0, 1,1)
}

```


### Tree Child

```{r,echo=F}
layout(matrix(1:2,ncol=2), width = c(2,1),height = c(1,1))
y_vals<-complete_dat$tc
cols <- rbPal(20)[as.numeric(cut(y_vals,breaks = 20))]

{
TernaryPlot(point='le',main='Complete Phylogenies',
            btip = expression(nu['+']),
            ctip = expression(nu['-']),
            atip = expression(nu['0']),
            axis.labels = seq(0,1,by=0.1),axis.cex=0.5
)
TernaryPoints(dat[1:59,c(3,1,2)],pch=19,col=cols,cex=2)
}
{
legend_image <- as.raster(matrix(rev(rbPal(20)), ncol=1))
plot(c(0,2),c(0,1),type = 'n', axes = F,xlab = '', ylab = '', main = 'Prop Tree-Child')
text(x=1.5, y = seq(0,1,l=5), labels = round(seq(min(y_vals),max(y_vals),l=5),digits = 3))
rasterImage(legend_image, 0, 0, 1,1)
}

```

```{r,echo=F}
layout(matrix(1:2,ncol=2), width = c(2,1),height = c(1,1))
y_vals<-recon_dat$tc
cols <- rbPal(20)[as.numeric(cut(y_vals,breaks = 20))]

{
TernaryPlot(point='le', main='Recon Phylogenies',
            btip = expression(nu['+']),
            ctip = expression(nu['-']),
            atip = expression(nu['0']),
            axis.labels = seq(0,1,by=0.1),axis.cex=0.5
)
TernaryPoints(dat[1:59,c(3,1,2)],pch=19,col=cols,cex=2)
}
{
legend_image <- as.raster(matrix(rev(rbPal(20)), ncol=1))
plot(c(0,2),c(0,1),type = 'n', axes = F,xlab = '', ylab = '', main = 'Prop Tree-Child')
text(x=1.5, y = seq(0,1,l=5), labels = round(seq(min(y_vals),max(y_vals),l=5),digits = 3))
rasterImage(legend_image, 0, 0, 1,1)
}

```

### Tips

```{r,echo=F}
layout(matrix(1:2,ncol=2), width = c(2,1),height = c(1,1))
y_vals<-complete_dat$tips
cols <- rbPal(20)[as.numeric(cut(y_vals,breaks = 20))]

{
TernaryPlot(point='le',main='Complete Phylogenies',
            btip = expression(nu['+']),
            ctip = expression(nu['-']),
            atip = expression(nu['0']),
            axis.labels = seq(0,1,by=0.1),axis.cex=0.5
)
TernaryPoints(dat[1:59,c(3,1,2)],pch=19,col=cols,cex=2)
}
{
legend_image <- as.raster(matrix(rev(rbPal(20)), ncol=1))
plot(c(0,2),c(0,1),type = 'n', axes = F,xlab = '', ylab = '', main = 'Tips')
text(x=1.5, y = seq(0,1,l=5), labels = round(seq(min(y_vals),max(y_vals),l=5),digits = 3))
rasterImage(legend_image, 0, 0, 1,1)
}

```

```{r,echo=F}
layout(matrix(1:2,ncol=2), width = c(2,1),height = c(1,1))
y_vals<-recon_dat$tips
cols <- rbPal(20)[as.numeric(cut(y_vals,breaks = 20))]

{
TernaryPlot(point='le', main='Recon Phylogenies',
            btip = expression(nu['+']),
            ctip = expression(nu['-']),
            atip = expression(nu['0']),
            axis.labels = seq(0,1,by=0.1),axis.cex=0.5
)
TernaryPoints(dat[1:59,c(3,1,2)],pch=19,col=cols,cex=2)
}
{
legend_image <- as.raster(matrix(rev(rbPal(20)), ncol=1))
plot(c(0,2),c(0,1),type = 'n', axes = F,xlab = '', ylab = '', main = 'Tips')
text(x=1.5, y = seq(0,1,l=5), labels = round(seq(min(y_vals),max(y_vals),l=5),digits = 3))
rasterImage(legend_image, 0, 0, 1,1)
}

```

### Reticulation Density


```{r,echo=F}
layout(matrix(1:2,ncol=2), width = c(2,1),height = c(1,1))
y_vals<-complete_dat$ratio
cols <- rbPal(20)[as.numeric(cut(y_vals,breaks = 20))]

{
TernaryPlot(point='le',main='Complete Phylogenies',
            btip = expression(nu['+']),
            ctip = expression(nu['-']),
            atip = expression(nu['0']),
            axis.labels = seq(0,1,by=0.1),axis.cex=0.5
)
TernaryPoints(dat[1:59,c(3,1,2)],pch=19,col=cols,cex=2)
}
{
legend_image <- as.raster(matrix(rev(rbPal(20)), ncol=1))
plot(c(0,2),c(0,1),type = 'n', axes = F,xlab = '', ylab = '', main = 'Rets/Tips')
text(x=1.5, y = seq(0,1,l=5), labels = round(seq(min(y_vals),max(y_vals),l=5),digits = 3))
rasterImage(legend_image, 0, 0, 1,1)
}

```

```{r,echo=F}
layout(matrix(1:2,ncol=2), width = c(2,1),height = c(1,1))
y_vals<-recon_dat$ratio
cols <- rbPal(20)[as.numeric(cut(y_vals,breaks = 20))]

{
TernaryPlot(point='le', main='Recon Phylogenies',
            btip = expression(nu['+']),
            ctip = expression(nu['-']),
            atip = expression(nu['0']),
            axis.labels = seq(0,1,by=0.1),axis.cex=0.5
)
TernaryPoints(dat[1:59,c(3,1,2)],pch=19,col=cols,cex=2)
}
{
legend_image <- as.raster(matrix(rev(rbPal(20)), ncol=1))
plot(c(0,2),c(0,1),type = 'n', axes = F,xlab = '', ylab = '', main = 'Rets/Tips')
text(x=1.5, y = seq(0,1,l=5), labels = round(seq(min(y_vals),max(y_vals),l=5),digits = 3))
rasterImage(legend_image, 0, 0, 1,1)
}




{
  TernaryPlot(point='le',main='Complete to Reconstructed Hybrid Proportions',
              btip = expression(nu['+']),
              ctip = expression(nu['-']),
              atip = expression(nu['0']),
              axis.labels = seq(0,1,by=0.1),axis.cex=0.5
  )
  TernaryArrows(complete_dat[,c(10,8,9)],recon_dat[,c(10,8,9)],length=0.05)
}



```
